Point to our own vx-citool

diff --git a/lib/vx/builder/templates/script_builder_v2/to_script.erb b/lib/vx/builder/templates/script_builder_v2/to_script.erb
--- a/lib/vx/builder/templates/script_builder_v2/to_script.erb
+++ b/lib/vx/builder/templates/script_builder_v2/to_script.erb
@@ -11,10 +11,10 @@ export TERM=xterm
 cd ~/
 
 rm -rf ~/citool
-git clone -q --depth=1 --branch=master https://github.com/vexor/vx-citool.git ~/citool || (
+git clone -q --depth=1 --branch=master https://github.com/pacoguzman/vx-citool.git ~/citool || (
   rs=$?
 
-  echo -e "${RED}The command 'git clone -q --depth=1 --branch=master https://github.com/vexor/vx-citool.git ~/citool' failed with code $rs${NORMAL}"
+  echo -e "${RED}The command 'git clone -q --depth=1 --branch=master https://github.com/pacoguzman/vx-citool.git ~/citool' failed with code $rs${NORMAL}"
 
   exit $rs
 )
